---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 3590.
--- DateTime: 2024/3/6 16:47
--- 更新：使用 zset
local blogLikedKeyPrefix = ARGV[1]
local blogId = ARGV[2]
local userId = ARGV[3]
local score = redis.call('TIME')[1] -- 获取当前时间戳
local blogLikedKey = blogLikedKeyPrefix .. blogId
-- 注意：redis 的 nil 对应到 lua 里面是 false，并不是 nil！
if (redis.call('zscore', blogLikedKey, userId)) then -- 如果用户已经点过赞了，就取消点赞
    redis.call('zrem', blogLikedKey, userId)
    return -1
end
-- 储存用户的点赞记录，表示它已经点过赞了
redis.call('zadd', blogLikedKey, score, userId)
return 0