---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 3590.
--- DateTime: 2024/3/5 22:19
local stockKey = KEYS[1]
local stock = tonumber(redis.call('get', stockKey)) -- 注意转为数值类型
if (stock <= 0) then
    return 1 -- 库存不充足，返回1
end
local orderKey = KEYS[2]
local userId = ARGV[1]
local isExist = tonumber(redis.call('sismember', orderKey, userId)) -- 成功则返回1，否则是0
if (isExist == 1) then
    return 2 -- 已经下过单了，返回2
end
-- 下面的情况就是既没有下过单，也由剩余库存，所以需要扣减库存，生成下单记录(orderKey --> userId)
redis.call('decr', stockKey) -- 扣减剩余库存
redis.call('sadd', orderKey, userId) -- 生成一个下单记录
                                       -- 生成订单
return 0